# Generated by Django 5.0.7 on 2024-08-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
        ('registration', '0006_registration_instagram_alter_registration_entry_hour_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['attendee'], name='unique_attendee_index'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(fields=('attendee',), name='unique_attendee_constraint'),
        ),
    ]
