# Generated by Django 5.0.7 on 2024-08-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_badge_unique_name_index_badge_unique_name_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
