# Generated by Django 5.0.7 on 2024-08-27 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0005_connection_unique_follower_followed_index_and_more'),
        ('registration', '0007_alter_registration_alcohol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='attendee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='registration.possibleattendees'),
        ),
    ]
