# Generated by Django 5.0.7 on 2024-08-27 12:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_alter_registration_alcohol_and_more'),
        ('sakura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captured_cards', to='registration.possibleattendees')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captured_by', to='sakura.question')),
            ],
            options={
                'ordering': ['attendee', 'card__serial_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='capturecard',
            constraint=models.UniqueConstraint(fields=('attendee', 'card'), name='unique_capture_card_attendee_card'),
        ),
    ]
