# Generated by Django 5.0.7 on 2024-08-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakura', '0002_capturecard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturecard',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
