# Generated by Django 5.0.7 on 2024-09-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakura', '0004_category_category_unique_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to='card-categories-front/'),
        ),
    ]
