# Generated by Django 5.0.7 on 2024-09-13 12:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_alter_registration_alcohol_and_more'),
        ('sakura', '0006_category_is_special_category_question_in_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('answer', models.TextField()),
                ('solved', models.BooleanField(default=False)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='registration.possibleattendees')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='sakura.question')),
            ],
            options={
                'ordering': ['attendee', 'card__serial_number'],
            },
        ),
    ]
