# Generated by Django 5.0.7 on 2024-08-10 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='possibleattendees',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='possibleattendees',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='attendees/'),
        ),
        migrations.AddField(
            model_name='possibleattendees',
            name='slug',
            field=models.SlugField(max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='possible_attendee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registered_attendee', to='registration.possibleattendees'),
        ),
    ]
