# Generated by Django 5.0.7 on 2024-08-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_possibleattendees_instagram_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='possibleattendees',
            index=models.Index(fields=['name', 'phone'], name='unique_name_phone_index'),
        ),
        migrations.AddConstraint(
            model_name='possibleattendees',
            constraint=models.UniqueConstraint(fields=('name', 'phone'), name='unique_name_phone_constraint'),
        ),
    ]
