# Generated by Django 5.0.7 on 2024-08-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_registration_slug_alter_registration_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='entry_hour',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='exit_hour',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
