# Generated by Django 5.0.7 on 2024-08-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_registration_instagram_alter_registration_entry_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='alcohol',
            field=models.CharField(blank=True, choices=[('1', 'Voy Manejando'), ('2', 'Un par de copitas y melo'), ('3', 'Si gotea repito'), ('4', 'Voy a hacer una elmada, traigame un balde')], max_length=1),
        ),
        migrations.AlterField(
            model_name='registration',
            name='vegetarian',
            field=models.CharField(choices=[('1', 'Vegetariano'), ('2', 'Me como lo que me pongan'), ('3', 'Soy judio'), ('4', 'Soy vegano, fastidioso y voy a llevar mi propia comida')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='registration',
            name='weed',
            field=models.CharField(choices=[('1', 'Nada, mi mama no me deja'), ('2', 'Par de ploncitos'), ('3', 'Si sobra me llevo'), ('4', 'Llevo quien me pilotee que voy al infinito y mas alla')], max_length=1),
        ),
    ]
